// Write a program which will draw the histogram for n integers from 0 to 99.  N is input by
// the user.  Each of the n numbers will be generated by calling rand() % 100.  The program
// will consist of two functions (i) to collect the frequency distribution of the numbers (ii) to
// print the histogram.  An example histogram is shown here.
// 0 – 9 |*********************
// 10 – 19 |************
// 20 – 29 |*************
// 30 – 39 |**
// …......
// 90 – 99 |***************


#include <stdio.h>
#include <stdlib.h>
#define MAX 20
int numbers;
int noofstars[MAX];
int array[MAX];   
void PrintHistogram();
void CollectDistibution(int numbers);
int main()
{
    printf("Enter Numbers: \n");
    scanf("%d", &numbers);
    CollectDistibution(numbers);
    PrintHistogram();
    
}

//pass by reference
void CollectDistibution(int numbers)
{   

    for (int i = 0; i < numbers; i++)
    {
        noofstars[i] = 0;
    }
    
    // divide into intervals
    for(int i = 0; i < numbers; i++)
    {
        //random number assigned to array 
        array[i] = rand() % 100;
        printf("array: %d\n", array[i]);
        //takes the tenth digit and assign it to that array
        //then increment that area by 1;
        noofstars[(int)(array[i] / 10)]++;
    }
    
}

void PrintHistogram()
{
    
    for (int i = 0; i < numbers; i++)
    {
        if (i*10 < 100)
        {
            printf("%d-%d",i*10, i*10 + 9);
        }
        if ((i * 10) >= 10 && (i*10) < 100)
        {
            printf("|");
        }
        else if((i*10) < 100)
        {
            printf("  |");
        }
        for (int j = 0; j < noofstars[i]; j++)
        {
            printf("*");
        }
        printf("\n");
        
    }
    
}

